basePath: /api
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.AuthTokens:
    description: Authentication tokens response payload
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      refresh_token:
        example: dGhpc2lzYXJlZnJlc2h0b2tlbg==...
        type: string
    type: object
  github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.CreateUserRequest:
    description: User registration request payload
    properties:
      email:
        example: john.doe@example.com
        type: string
      first_name:
        example: John
        maxLength: 50
        minLength: 2
        type: string
      knowledge_level:
        enum:
        - beginner
        - intermediate
        - advanced
        example: beginner
        type: string
      last_name:
        example: Doe
        maxLength: 50
        minLength: 2
        type: string
      middle_name:
        example: Michael
        type: string
      password:
        example: secret123
        minLength: 6
        type: string
      phone:
        example: "+77010000000"
        type: string
    required:
    - email
    - first_name
    - knowledge_level
    - last_name
    - password
    type: object
  github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.LoginRequest:
    description: Login request payload
    properties:
      email:
        example: admin@mai.ru
        type: string
      password:
        example: qwe123
        type: string
    required:
    - email
    - password
    type: object
  github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.RefreshRequest:
    description: Refresh token request payload
    properties:
      refresh_token:
        example: dGhpc2lzYXJlZnJlc2h0b2tlbg==...
        type: string
    required:
    - refresh_token
    type: object
  github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.UserResponse:
    description: User response payload.
    properties:
      created_at:
        example: "2025-11-12T19:45:00Z"
        type: string
      email:
        example: user@mail.ru
        type: string
      first_name:
        example: John
        type: string
      id:
        example: a8098c1a-f86e-11da-bd1a-00112444be1e
        type: string
      knowledge_level:
        example: beginner
        type: string
      last_name:
        example: Doe
        type: string
      middle_name:
        example: Michael
        type: string
      phone:
        example: "+77010000000"
        type: string
      portfolio:
        example: Experienced backend developer with 5+ years in Go.
        type: string
      rating:
        description: Tutor-specific fields (optional)
        example: 4.8
        type: number
      role:
        example: tutor
        type: string
      testimonials_count:
        example: 12
        type: integer
      updated_at:
        example: "2025-11-12T19:45:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample Gin server with Swagger
  title: BMSTU IT Courses API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.AuthTokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: Login user
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token request to logout
        in: body
        name: logout
        required: true
        schema:
          $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Logout user (invalidate refresh token)
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token request
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.AuthTokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: Refresh access token
      tags:
      - Auth
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.UserResponse'
            type: array
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: New user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create user
      tags:
      - Users
  /users/{id}:
    delete:
      parameters:
      - description: User ID (uuid)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Delete user by ID
      tags:
      - Users
    get:
      parameters:
      - description: User ID (uuid)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_maxcore25_bmstu-it-courses_backend_internal_auth_dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get user by ID
      tags:
      - Users
    patch:
      consumes:
      - application/json
      parameters:
      - description: User ID (uuid)
        in: path
        name: id
        required: true
        type: string
      - description: User update data
        in: body
        name: user
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update user by ID
      tags:
      - Users
swagger: "2.0"
